apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-chat-migration-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.groupchatmigration.replicas }}
  selector:
    matchLabels:
      app: group-chat-migration-service
  template:
    metadata:
      labels:
        app: group-chat-migration-service
    spec:
      containers:
      - name: group-chat-migration-service
        image: {{ .Values.registryServer }}/group-chat-migration-service:{{ .Values.groupchatmigration.image }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: common-config
        - secretRef:
            name: avas2tecr 
        ports:
        - containerPort: {{ .Values.groupchatmigration.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: group-chat-migration-service-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.groupchatmigration.port }}
  selector:
    app: group-chat-migration-service